##
# $ ansible-playbook aws-generate-inventory.yml
##

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    environment: "{{ ENV | default('preproduction')}}"
    version: "{{ VER | default('latest') }}"
    inventory_dict: {}

  vars_files:
    - "./vars/aws-{{ environment }}-{{ version }}.yml"

  tasks:
    - name:  Extract EC2 instance information
      include_role:
        name: iac_aws_instance
      vars:
        action: add-public-ip-inventory
        instance: "{{ item.name }}"
        project: "{{ project_id }}"
        group: "ansiblenodes"
      loop: "{{ instances }}"

    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
        var: aws_inventory

- name: Place the inventory file at the classroom webserver
  hosts: classroom01
  remote_user: ec2-user
  become: true
  vars:
    ansible_ssh_private_key_file: ../../ansiblepoc.pem
    aws_inventory_file: inventory_refined
  tasks:
    - name: Write down the inventory file
      template:
        src: inventory_refined.j2
        dest: "/var/www/html/files/{{ aws_inventory_file }}"
        owner: root
        group: root
        mode: 0644

    - name: Show the classroom01 URL (facts)
      debug:
        msg:
          - "{{ base_url }}"
          - "{{ base_url }}/{{ aws_inventory_file }}"
      vars:
        base_url: "http://{{ hostvars.localhost.aws_inventory.classroom01.public_dns_name }}/files"
...
